description = 'OpenRune Server Studio service'

apply plugin: 'application'
apply plugin: 'org.jetbrains.kotlin.jvm'

kotlin {
    jvmToolchain(21)
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21
    }
}

dependencies {
    implementation project(':Protocol')

    implementation platform("io.ktor:ktor-bom:${ktorVersion}")
    implementation "io.ktor:ktor-server-core-jvm"
    implementation "io.ktor:ktor-server-netty-jvm"
    implementation "io.ktor:ktor-server-content-negotiation-jvm"
    implementation "io.ktor:ktor-server-status-pages-jvm"
    implementation "io.ktor:ktor-serialization-jackson-jvm"

    implementation "dev.or2:filesystem:${openruneFileStoreVersion}"
    implementation "dev.or2:filestore:${openruneFileStoreVersion}"
    implementation "org.tomlj:tomlj:1.1.1"
    implementation "org.jetbrains.kotlin:kotlin-compiler-embeddable:${openruneKotlinSemanticVersion}"

    testImplementation "org.jetbrains.kotlin:kotlin-test-junit5"
    testImplementation "io.ktor:ktor-server-test-host-jvm"
}

application {
    mainClass = 'com.openrune.studio.service.StudioServiceMainKt'
}
